In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [2]:
df=pd.read_csv("titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [4]:
target=df.Survived
inputs=df.drop('Survived',axis='columns')

In [5]:
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [6]:
inputs

     Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
888       3  female   NaN  23.4500
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[891 rows x 4 columns]

In [7]:
dummies=pd.get_dummies(inputs.Sex)
dummies.head()

   female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [8]:
inputs=pd.concat([inputs,dummies],axis='columns')
inputs.head()

   Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [10]:
inputs.drop('Sex',axis='columns',inplace=True)
inputs.head()

   Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [11]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [12]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [20]:
inputs.Age=inputs.Age.fillna(inputs.Age.mean())
inputs.head(6)

   Pclass        Age     Fare  female  male
0       3  22.000000   7.2500       0     1
1       1  38.000000  71.2833       1     0
2       3  26.000000   7.9250       1     0
3       1  35.000000  53.1000       1     0
4       3  35.000000   8.0500       0     1
5       3  29.699118   8.4583       0     1

In [21]:
x_train,x_test,y_train,y_test=train_test_split(inputs,target,test_size=0.30)

In [22]:
x_train

     Pclass        Age      Fare  female  male
466       2  29.699118    0.0000       0     1
603       3  44.000000    8.0500       0     1
269       1  35.000000  135.6333       1     0
536       1  45.000000   26.5500       0     1
533       3  29.699118   22.3583       1     0
..      ...        ...       ...     ...   ...
713       3  29.000000    9.4833       0     1
167       3  45.000000   27.9000       1     0
863       3  29.699118   69.5500       1     0
581       1  39.000000  110.8833       1     0
628       3  26.000000    7.8958       0     1

[623 rows x 5 columns]

In [23]:
x_test

     Pclass        Age     Fare  female  male
600       2  24.000000  27.0000       1     0
815       1  29.699118   0.0000       0     1
740       1  29.699118  30.0000       0     1
142       3  24.000000  15.8500       1     0
42        3  29.699118   7.8958       0     1
..      ...        ...      ...     ...   ...
241       3  29.699118  15.5000       1     0
234       2  24.000000  10.5000       0     1
799       3  30.000000  24.1500       1     0
653       3  29.699118   7.8292       1     0
531       3  29.699118   7.2292       0     1

[268 rows x 5 columns]

In [24]:
y_train

466    0
603    0
269    1
536    0
533    1
      ..
713    0
167    0
863    0
581    1
628    0
Name: Survived, Length: 623, dtype: int64

In [25]:
y_test

600    1
815    0
740    1
142    1
42     0
      ..
241    1
234    0
799    0
653    1
531    0
Name: Survived, Length: 268, dtype: int64

In [26]:
model=GaussianNB()

In [27]:
model.fit(x_train,y_train)

GaussianNB()

In [30]:
x_test[:10]

     Pclass        Age      Fare  female  male
600       2  24.000000   27.0000       1     0
815       1  29.699118    0.0000       0     1
740       1  29.699118   30.0000       0     1
142       3  24.000000   15.8500       1     0
42        3  29.699118    7.8958       0     1
377       1  27.000000  211.5000       0     1
611       3  29.699118    7.0500       0     1
556       1  48.000000   39.6000       1     0
214       3  29.699118    7.7500       0     1
633       1  29.699118    0.0000       0     1

In [29]:
y_test[:10]

600    1
815    0
740    1
142    1
42     0
377    0
611    0
556    1
214    0
633    0
Name: Survived, dtype: int64

In [31]:
model.predict(x_test[:10])

array([1, 0, 0, 1, 0, 1, 0, 1, 0, 0], dtype=int64)

In [32]:
model.predict_proba(x_test[:10])

array([[2.31803566e-02, 9.76819643e-01],
       [9.34421715e-01, 6.55782850e-02],
       [9.33847325e-01, 6.61526748e-02],
       [5.69286113e-02, 9.43071389e-01],
       [9.93009869e-01, 6.99013084e-03],
       [1.38071308e-06, 9.99998619e-01],
       [9.92974648e-01, 7.02535232e-03],
       [5.49389932e-03, 9.94506101e-01],
       [9.93004107e-01, 6.99589332e-03],
       [9.34421715e-01, 6.55782850e-02]])